# Generated by Django 4.2.4 on 2023-08-20 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.ForeignKey(
                        db_column="id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("resume", models.TextField(blank=True, null=True)),
                ("cover", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Profile",
                "managed": True,
            },
        ),
    ]
