# Generated by Django 4.2.4 on 2023-08-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0003_alter_profile_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="distance",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
