# Generated by Django 4.2.4 on 2023-08-20 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Providers",
            fields=[
                ("provider_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="Name", max_length=100, null=True
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                "db_table": "Providers",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Urls",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("keywords", models.CharField(blank=True, max_length=1024, null=True)),
                ("url", models.CharField(blank=True, max_length=2048, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        db_column="provider",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ListingFeed.providers",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Urls",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Indeedlistings",
            fields=[
                (
                    "listing_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("location", models.CharField(blank=True, max_length=32, null=True)),
                ("distance", models.CharField(blank=True, max_length=256, null=True)),
                ("published", models.DateTimeField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("link", models.CharField(blank=True, max_length=2048, null=True)),
                ("flag", models.IntegerField(blank=True, null=True)),
                ("remove", models.IntegerField(blank=True, null=True)),
                ("finish", models.IntegerField(blank=True, null=True)),
                ("in_progress", models.IntegerField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ListingFeed.urls",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        default=1,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "IndeedListings",
                "managed": True,
            },
        ),
    ]
