# Generated by Django 4.2.4 on 2023-08-21 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ListingFeed", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indeedlistings",
            name="user_id",
        ),
        migrations.AddField(
            model_name="indeedlistings",
            name="eta",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indeedlistings",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="indeedlistings",
            name="distance",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
    ]
