# Generated by Django 4.2.4 on 2023-08-21 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "ListingFeed",
            "0002_remove_indeedlistings_user_id_indeedlistings_eta_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indeedlistings",
            name="user",
        ),
        migrations.AddField(
            model_name="indeedlistings",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
