# Generated by Django 4.2.4 on 2023-08-21 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ListingFeed", "0003_remove_indeedlistings_user_indeedlistings_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indeedlistings",
            name="user_id",
        ),
    ]
