# Generated by Django 4.2.4 on 2023-08-21 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ListingFeed", "0004_remove_indeedlistings_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="indeedlistings",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
