# Generated by Django 4.2.4 on 2023-08-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ListingFeed", "0005_indeedlistings_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhraseList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phrases", models.CharField(max_length=4096)),
            ],
        ),
    ]
